const nome = 'Luiz Otavio';
const sobrenome = 'Miranda';
let idade, peso, altura, imc;
idade = 30;
peso = 84;
altura = 1.80;
imc = peso/ (altura * altura);
let anoNascimento = 2019 - idade;
console.log(nome, sobrenome, 'tem',idade,'anos, pesa',peso, 'kg tem', altura, 'de altura e seu IMC é de', imc);
console.log(`${nome} nasceu em ${anoNascimento}`);