Algoritmo "ExercicioCirculo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/03/2023
Var
// Seção de Declarações das variáveis 
r, area: real

Inicio
escreva("Digite o valor do raio do circulo: ")
leia(r)
area <-(r * r)*3.14159

escreva("Area= ", area: 4:3)


Fimalgoritmo